//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTranslationLanguge
    {
        public int Id { get; set; }
        public Nullable<int> Id_Category { get; set; }
        public string Title { get; set; }
        public string SEO { get; set; }
        public Nullable<int> Id_Language { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
    }
}
