//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTranslationLanguage
    {
        public int Id { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public string Title { get; set; }
        public string SEO { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Id_Language { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Product Product { get; set; }
    }
}
